version: '3'

services:
  discovery:
    build: ./eureka-server
    container_name: discovery
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 1000

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    container_name: db

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 1000
    depends_on:
      discovery:
        condition: service_healthy

  wallet-service:
    build:
      context: ./wallet-service
    container_name: wallet-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 1000
    depends_on:
      discovery:
        condition: service_healthy

  transfer-service:
    build:
      context: ./transfer-service
    container_name: transfer-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 5s
      retries: 1000
    depends_on:
      discovery:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - '8765:8765'
    expose:
      - '8765'
    depends_on:
      user-service:
        condition: service_healthy
      wallet-service:
        condition: service_healthy
      transfer-service:
        condition: service_healthy